# Generated by Django 5.0.6 on 2024-05-22 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_of_purchase',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
